services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: unless-stopped
    depends_on:
      - node_exporter
      - cadvisor
    networks:
      - home-server

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"
    restart: unless-stopped
    networks:
      - home-server

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_SECURITY_ALLOW_EMBEDDING=true
    volumes:
      - grafana-data:/var/lib/grafana
#      - ./grafana_config:/etc/grafana/
    restart: unless-stopped
    depends_on:
      - prometheus
    networks:
      - home-server

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    privileged: true
    ports:
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /:/rootfs:ro
      - /var/run:/var/run:ro
#      - /var/lib/docker:/var/lib/docker:ro
    restart: unless-stopped
    networks:
      - home-server

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml
    command: -config.file=/etc/loki/loki-config.yml
    restart: unless-stopped
    networks:
      - home-server

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log:/var/log
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
      - ./GeoLite2-City.mmdb:/etc/promtail/GeoLite2-City.mmdb:ro
    command: -config.file=/etc/promtail/promtail-config.yml
    restart: unless-stopped
    networks:
      - home-server


  gotify:
    container_name: gotify
    image: gotify/server
    ports:
      - 8923:80
    environment:
      GOTIFY_DEFAULTUSER_PASS: ${GOTIFY_DEFAULTUSER_PASS}
      TZ: "Europe/Bucharest"
    volumes:
      - ./gotify_data:/app/data
      - ./gotify_config/config.yml:/etc/gotify/config.yml
    networks:
      - home-server

volumes:
  grafana-data:

networks:
  home-server:
    external: true
